version: '3.8'

services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: auth_service_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestion_opiniones
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_network

volumes:
  postgres_data:
    driver: local

networks:
  auth_network:
    driver: bridge


